### ISSUE TITLE
Overview document: explanations major classes

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#13]
Briefly explain the meanings of the classes.
Basic:
- Molecule
- Atom
- MoleculeWidget
- Cylinder; Cylinders
- Sphere; Spheres

Technical:
- MainWindow; Ui_MainWindow
- Drawer
- Vao

**Comment by adrianusler** [comment]
This might be unnecessary because of the Sphinx setup? @ab5424 @flrnslbch

**Comment by ab5424** [comment]
Yes
