### ISSUE TITLE
Wrong precision in cylinder rendering

### ISSUE THREAD

**Issue by RealUranar** [Molara-Lab/Molara#292]
Inconsistent use of float and double precision in cylinder rendering. This leads to an error when only drawing one cylinder with the arrays defined as np.float32.

**Comment by RealUranar** [comment]
Fixed, ready to merge

**Comment by adrianusler** [comment]
> Fixed, ready to merge

Nice! Please open a pull request.

**Comment by adrianusler** [comment]
Please remember to create a Pull Request, @RealUranar :)
