### ISSUE TITLE
Update branch name convention in CONTRIBUTING.md

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#296]
Currently, it still says
```
Naming Convention:
- For features: feature-<issue-number>-<description>. Example: feature-123-user-authentication.
- For bug fixes: bug-<issue-number>-<description>. Example: bug-456-payment-gateway-error.
```

Although we have agreed that we now name branches like `feature/123-a-message`

**Comment by adrianusler** [comment]
What do you think about this @Michel-Heinz @ab5424 @GereonFeldmann?

**Comment by ab5424** [comment]
I don't have an opinion on that.

**Comment by Michel-Heinz** [comment]
I am all for it. If we use feature/... it will be interpreted as a directory and this simplifies navigation of branches in vscode and gitkraken.
