### ISSUE TITLE
readthedocs.org documentation

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#298]
Should we also create a project documentation on readthedocs.org? I think that this should be rather straightforward

**Comment by flrnslbch** [comment]
I have already setup a github pages documentation. It will look exactly like on readthedocs only the url will be molaralab.github.io/molara/
See PR #284

**Comment by adrianusler** [comment]
I know that we are getting the Sphinx documentation @flrnslbch. The question was if we do readthedocs.org on top.

The reason why I ask is this: readthedocs is a well-known "brand" in which people trust. If I start working with a package, it is the first thing that I look out for on Google. I think that it would also increase visibility.

**Comment by ab5424** [comment]
@adrianusler What do we need readthedocs for that the shpinx doc on gh pages can't do? I don't really understand.

**Comment by adrianusler** [comment]
It's not about what it can do, but just about the name. Like I said, readthedocs is an established brand, so to say

**Comment by ab5424** [comment]
@adrianusler I'm fine with it then, but I personally never though about that.

**Comment by adrianusler** [comment]
https://molara.readthedocs.io/en/latest/
