### ISSUE TITLE
Increase test coverage of crystal.py, importer.py, importer_crystal.py, molecule.py, structure.py

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#303]
I am on it (see PR #305).

**Comment by adrianusler** [comment]
@ab5424 I think that the testing action doesn't install pymatgen right now, so we can't get full coverage. Can/should we change this?

**Comment by adrianusler** [comment]
Is the `PymatgenImporter` able to parse CIF files, @ab5424? If so, it would be nice to have some of those in the examples folder. I could then include CIF import in `test_crystal`.

**Comment by ab5424** [comment]
> Is the `PymatgenImporter` able to parse CIF files, @ab5424? If so, it would be nice to have some of those in the examples folder. I could then include CIF import in `test_crystal`.

Yes.

**Comment by Michel-Heinz** [comment]
Can this be closed now?

**Comment by adrianusler** [comment]
I think I'd like to have a look if I can still increase coverage a bit more, @Michel-Heinz
