### ISSUE TITLE
Remove Qt-related tests from windows workflow, clean up test.yml

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#314]
In the branch housekeeping/302-create-tests, I have now included a test of the `Renderer` class that makes use of pytest-qt.
- [x] remove qt tests from windows workflow
- [x] clean up test.yml

**Comment by ab5424** [comment]
@adrianusler I deactivated the test on windows.

**Comment by adrianusler** [comment]
According to [The troubleshooting section of pytest-qt](https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html), it should be sufficient to install these packages:
- libxcb-icccm4
- libxcb-image0
- libxcb-keysyms1
- libxcb-randr0
- libxcb-render-util0
- libxcb-xinerama0
- libxcb-xfixes0
- x11-utils

It think that currently, we install more packages in the test.yml file
