### ISSUE TITLE
Program Does Not Close Immediately with Command+C and Results in Segmentation Fault

### ISSUE THREAD

**Issue by NvStaalduinen** [Molara-Lab/Molara#341]
### Description:
I have observed a potential issue with Molara when attempting to close it via the terminal using the Command+C shortcut. Instead of terminating quickly and cleanly, the program takes an unusually long time to respond to the interrupt signal. Eventually, it terminates but results in a segmentation fault. This behavior is inconsistent with the expected quick and clean termination process typical for command line applications similar to Molden.

### Steps to Reproduce:

- Open the terminal.

- Run the program in question with ```molara coord.xyz```

- Once the program is running, try to terminate it using Command+C.

### Expected Behavior:
The program should terminate immediately and cleanly without any error messages or faults when Command+C is used.

### Actual Behavior:
The program takes a significant amount of time to respond to Command+C. Eventually, it terminates but results in a segmentation fault, indicating an abnormal termination process.

### Environment:

Operating System: macOS Sonoma
Program Version:  0.0.1 

### Additional Notes:
The problem may indicate improper handling of SIGINT signals, or resources not being properly managed on program termination. Fast and reliable exiting is important to my workflow, at least, since sometimes I just want to quickly open a molecule, look at it, close it with Command+C, and move on to the next molecule.

**Comment by Michel-Heinz** [comment]
Thanks for submitting, I remember this issue, but the fix got somehow lost months ago.

**Comment by Michel-Heinz** [comment]
The bug should be fixed now!

**Comment by NvStaalduinen** [comment]
Works like a charm. Molara is very useful. Thanks!
