### ISSUE TITLE
Molara Fails to Display Molecules from .xyz Files with Lowercase Atomic Symbols

### ISSUE THREAD

**Issue by NvStaalduinen** [Molara-Lab/Molara#343]
### Issue Description:
Molara currently expects atomic symbols in .xyz files to be in uppercase format (e.g., "C" for carbon, "H" for hydrogen). When attempting to load .xyz files containing lowercase atomic symbols (e.g., "c" for carbon, "h" for hydrogen), the tool fails to correctly recognize and display the molecules.

### Steps to Reproduce:

1. Open the following file with Molara ```molara water.xyz``` :
```
 3
 energy: -5.070544445960 gnorm: 0.000055339110 xtb: 6.6.1 (8d0f1dd)
o           -0.27298148329399        0.06943001399675        0.00000000000000
h            0.42780020340973        0.72444650730362       -0.00000000000000
h            0.14518127988426       -0.79387652130037        0.00000000000000
```

### Expected Behavior:

The tool should be able to handle .xyz files with atomic symbols in either uppercase or lowercase. I understand that uppercase atomic symbols are more common. But some programs still provide lowercase atomic symbols. And QC programs like xtb do not care whether they are uppercase or lowercase. 

### Actual Behavior:

The tool fails to recognize and display the molecular structure when the .xyz file contains atomic symbols in lowercase.
############
    atom = Atom(atomic_number, coordinates[i])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#######
    self.symbol = elements[atomic_number]["symbol"]
                  ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 0


### Suggested Fix:

Implement a function in the tool that converts all atomic symbols in the .xyz file to uppercase before processing the file. This would ensure compatibility with .xyz files regardless of the case used for atomic symbols.

**Comment by Michel-Heinz** [comment]
I am on it!

**Comment by NvStaalduinen** [comment]
Thanks!
