### ISSUE TITLE
Implement release workflow for trusted release on pypi and configure wheel builds

### ISSUE THREAD

**Issue by ab5424** [Molara-Lab/Molara#346]
I applied for an organisation on pypi. Once this is approved I will configure the release workflow so that we can trigger a release directly here on github.

**Comment by Michel-Heinz** [comment]
Very very nice :) We will also need to setup precompiled versions for every operating system.

**Comment by ab5424** [comment]
Yes, using `[cibuildwheel](https://github.com/pypa/cibuildwheel)`. That shouldn't be a big issue.

**Comment by ab5424** [comment]
Apparently the approval for an organisation currently takes months. For now I registered Molara under my name, I will transfer it later.
