### ISSUE TITLE
 Issue: Molara Doesn't Support .log and .trj Files

### ISSUE THREAD

**Issue by NvStaalduinen** [Molara-Lab/Molara#365]
### Description
When attempting to import molecular dynamics trajectory files with `.log` or `.trj` extensions into a molecular visualization program, an error occurs:
```python
molara/Structure/io/importer.py", line 493, in __init__
self._importer = self._IMPORTER_BY_SUFFIX[suffix](path)
                     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: '.log'
```

This error indicates that these file types are not supported by the program's importer system.

## Impact
Users cannot visualize or analyze molecular dynamics trajectories with .log or .trj files.

## Suggested Fixes
* Add Import Support: Update the program to support .log and .trj file extensions.
* Improve Error Handling: Include more informative error messages for unsupported file formats or supported formats a user can choose from.
* Update Documentation: Provide a list of supported file formats to guide users.

**Comment by Michel-Heinz** [comment]
Can you rovide example files for .log and .trj files, or tell us how they are formatted?
