### ISSUE TITLE
Store molara settings files per default in ~/.molara/

### ISSUE THREAD

**Issue by ab5424** [Molara-Lab/Molara#382]
It is not a good idea to save the settings files into the installation path of a library.

**Comment by Michel-Heinz** [comment]
Yes that would be wise! I was asking myself this question this weekend

**Comment by adrianusler** [comment]
If we create a directory outside of the molara install directory, it would be nice to have an uninstaller that cleans it up, right?

**Comment by ab5424** [comment]
A textfile of a few kB shouldn't matter.

**Comment by Michel-Heinz** [comment]
How can we move the default.json settings file to that dir upon installation?

**Comment by ab5424** [comment]
> Does the "~" operator work in Windows?

Sure. Or `Path.home()`.

**Comment by Michel-Heinz** [comment]
@ab5424 I created a branch for this, can you please change the installation script in order to create the ~/.molara directory upon installation?

**Comment by Michel-Heinz** [comment]
Okay good idea :+1:

**Comment by ab5424** [comment]
Closed by #464
