### ISSUE TITLE
Clean up structure_widget

### ISSUE THREAD

**Issue by Michel-Heinz** [Molara-Lab/Molara#392]
More specific discussion about cleaning up the code of structure_widget. #387

**Comment by adrianusler** [comment]
- [ ] condense `set_view_to_x/y/z_axis` into one function `set_view_to_axis`
- [ ] update_measurement_selected_atoms and `update_builder_selected_atoms` could maybe be simplified, combined, and in parts moved to a different module
- [ ] simplify `toggle_unit_cell_boundaries`: let the Crystal object generate the box specifics
- [ ] `mouseMoveEvent`: move `camera.update` und `self.update()` out of if statement
- [ ] move `event.x() not in range(self.width())` in front of if statements
