### ISSUE TITLE
Pytest: test if exceptions are raised

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#448]
[Stackoverflow on testing exceptions](https://stackoverflow.com/a/29855337/11339443)
Something along the lines of
```
    with pytest.raises(Exception) as e_info:
        x = 1 / 1
```

**Comment by ab5424** [comment]
I've previously added some, like https://github.com/Molara-Lab/Molara/blob/main/tests/molara/Structure/io/test_importer_crystal.py#L45 or https://github.com/Molara-Lab/Molara/blob/main/tests/molara/Structure/test_crystal.py#L193
