### ISSUE TITLE
Simplify rendering.py

### ISSUE THREAD

**Issue by Michel-Heinz** [Molara-Lab/Molara#503]
There is a lot of code duplication going on in rendering.py especially when it comes to drawing and removing objects. It needs to be cleaned up.

**Comment by adrianusler** [comment]
I agree! For instance, code like
```python
glBindVertexArray(sphere["vao"])
glDrawElementsInstanced(
    GL_TRIANGLES,
    sphere["n_vertices"],
    GL_UNSIGNED_INT,
    None,
    sphere["n_instances"],
)
```
appears a lot. Also code pieces similar to
```python
glBindBuffer(GL_ARRAY_BUFFER, 0)
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0)
for buffer in number["buffers"]:
    glDeleteBuffers(1, buffer)
glDeleteVertexArrays(1, number["vao"])
```

I think it's a good first step to make functions out of these. This will make it easier to see larger structures in the code and maybe simplify the code even more.
