### ISSUE TITLE
 Molara Installation via PyPI Does Not Support Cursor-Based Molecule Rotation or Movement

### ISSUE THREAD

**Issue by NvStaalduinen** [Molara-Lab/Molara#531]
## Description: 

After installing Molara 0.0.2 using ```pip install molara``` from PyPI, the molecular visualizer does not allow for rotation or movement of the molecule using the cursor. This functionality works as expected when installing Molara from the main branch at commit dad3e22  using ```pip install path/to/Molara ```.

## Environment:

	•	Operating System: macOS 15.0.1
	•	Python Version: 3.12.7
	•	Molara Installation Source: PyPI 0.0.2

## Steps to Reproduce:

	1.	Install Molara from PyPI: pip install molara
	2.	Open Molara and attempt to rotate or move the molecule using the cursor.

## Expected Behavior: 
The molecule should respond to cursor actions, allowing rotation and movement.

## Observed Behavior: 
The molecule remains static and does not respond to cursor-based manipulation.

## Workaround: 
Installing Molara from the main branch  (pip install path/to/Molara) allows for proper rotation and movement.

**Comment by adrianusler** [comment]
Thanks for making us aware of this problem, @NvStaalduinen!

**Comment by adrianusler** [comment]
@ab5424 Do you happen to know what might be a difference between the installation from source and the PyPI installation?

**Comment by ab5424** [comment]
I'll have a look

**Comment by ab5424** [comment]
I triggered a new release which seems to have fixed the issue for me, cn you try updating `molara` @NvStaalduinen ?

**Comment by NvStaalduinen** [comment]
Thanks, works perfectly fine now. Issue can be closed.
